app = "stable-diffusion-webui"
primary_region = "ord"
vm.size = "l40s"
swap_size_mb = 32768

[mounts]
source = "data"
destination = "/app"

[[services]]
internal_port = 7860
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
handlers = ["http"]
port = 80
